### ISSUE TITLE
[feat] list - 모두 선택 기능

### ISSUE THREAD

**Issue by eonseok-jeon** [DO-SOPT-sims-toy-project/github-follow-detector#8]
## 🛠 Issue

- 체크박스 모두 선택 / 해제 하는 기능 구현

## 📝 To-do

- [x] 각각의 팔로워 선택할 수 있게함
- [x] 모두 선택할 수 있게함
- [x] 모두 해제할 수 있게함
